-- vbamod_test.lua — VBA 运行时库断言测试（VBA 语义锚点）
-- 跑法: luajit vbamod_test.lua  （退出码 0=全过）
-- 跑法: cd libs/udf && luajit vbamod_test.lua
local vba = dofile('vbamod.lua')
local ok, fail = 0, 0
local function eq(name, got, want)
  local g, w = tostring(got), tostring(want)
  if type(got) == "number" and type(want) == "number" and math.abs(got - want) < 1e-6 then g = w end
  if g == w then ok = ok + 1
  else fail = fail + 1; print(string.format("FAIL %-28s got=[%s] want=[%s]", name, g, w)) end
end

-- ===== Strings =====
eq("Len", vba.Len("hello"), 5)
eq("Len empty", vba.Len(""), 0)
eq("Left", vba.Left("hello", 2), "he")
eq("Left 0", vba.Left("hello", 0), "")
eq("Left over", vba.Left("hello", 10), "hello")
eq("Right", vba.Right("hello", 2), "lo")
eq("Mid", vba.Mid("hello", 2, 3), "ell")
eq("Mid open", vba.Mid("hello", 2), "ello")
eq("Mid start0", vba.Mid("hello", 0, 3), "")
eq("Mid len0", vba.Mid("hello", 2, 0), "")
eq("InStr", vba.InStr("hello", "l"), 3)
eq("InStr miss", vba.InStr("hello", "x"), 0)
eq("InStr start", vba.InStr(4, "hello", "l"), 4)
eq("InStr empty", vba.InStr("hello", ""), 1)
eq("InStr empty4", vba.InStr(4, "hello", ""), 4)
eq("InStrRev", vba.InStrRev("hello", "l"), 4)
eq("InStrRev miss", vba.InStrRev("hello", "x"), 0)
eq("Replace all", vba.Replace("aaa", "a", "b"), "bbb")
eq("Replace cnt", vba.Replace("aaa", "a", "b", 2, 1), "aba")
eq("Replace prefix", vba.Replace("banana", "na", "X"), "baXX")
eq("Trim", vba.Trim("  a  "), "a")
eq("LTrim", vba.LTrim("  a  "), "a  ")
eq("RTrim", vba.RTrim("  a  "), "  a")
eq("UCase", vba.UCase("aBc"), "ABC")
eq("LCase", vba.LCase("AbC"), "abc")
eq("Asc", vba.Asc("A"), 65)
eq("Chr", vba.Chr(65), "A")
eq("Space", vba.Space(3), "   ")
eq("String c", vba.String(3, "A"), "AAA")
eq("String n", vba.String(3, 65), "AAA")
eq("StrReverse", vba.StrReverse("abc"), "cba")
eq("Split1", vba.Split("a,b,c", ",")[1], "a")
eq("Split3", vba.Split("a,b,c", ",")[3], "c")
eq("Join", vba.Join({ "a", "b", "c" }, ","), "a,b,c")
eq("StrComp lt", vba.StrComp("a", "b"), -1)
eq("StrComp gt", vba.StrComp("b", "a"), 1)
eq("StrComp text", vba.StrComp("A", "a", 1), 0)
eq("Val num", vba.Val("123abc"), 123)
eq("Val comma", vba.Val("1,234.5"), 1234.5)
eq("Val hex", vba.Val("&HFF"), 255)
eq("Val alpha", vba.Val("abc"), 0)
eq("Val sci", vba.Val("-12.5e2"), -1250)
eq("Filter", vba.Join(vba.Filter({ "a", "ab", "c" }, "a"), ","), "a,ab")

-- ===== Conversion =====
eq("CBool 1", tostring(vba.CBool(1)), "true")
eq("CBool 0", tostring(vba.CBool(0)), "false")
eq("CInt 2.5", vba.CInt(2.5), 2)
eq("CInt 3.5", vba.CInt(3.5), 4)
eq("CInt -2.5", vba.CInt(-2.5), -2)
eq("CLng 2.5", vba.CLng(2.5), 2)
eq("CByte 2.5", vba.CByte(2.5), 2)
eq("CByte clamp", vba.CByte(300), 255)
eq("CStr int", vba.CStr(1234), "1234")
eq("CStr dbl", vba.CStr(1.5), "1.5")
eq("Fix neg", vba.Fix(-2.5), -2)
eq("Int neg", vba.Int(-2.5), -3)
eq("Hex", vba.Hex(255), "FF")
eq("Oct", vba.Oct(8), "10")
eq("VarType str", vba.VarType("x"), 8)
eq("VarType int", vba.VarType(1), 2)
eq("VarType dbl", vba.VarType(1.5), 5)
eq("VarType bool", vba.VarType(true), 11)
eq("VarType nil", vba.VarType(nil), 0)
eq("VarType arr", vba.VarType({}), 8192)
eq("TypeName int", vba.TypeName(1), "Integer")
eq("TypeName str", vba.TypeName("x"), "String")
eq("TypeName dbl", vba.TypeName(1.5), "Double")
eq("TypeName bool", vba.TypeName(true), "Boolean")
eq("TypeName arr", vba.TypeName({}), "Variant()")

-- ===== Math =====
eq("Abs", vba.Abs(-5), 5)
eq("Sgn neg", vba.Sgn(-3), -1)
eq("Sgn zero", vba.Sgn(0), 0)
eq("Sgn pos", vba.Sgn(3), 1)
eq("Sqr", vba.Sqr(9), 3)
eq("Round 2.5", vba.Round(2.5), 2)
eq("Round 3.5", vba.Round(3.5), 4)
eq("Round 0.5", vba.Round(0.5), 0)
eq("Round 1.5", vba.Round(1.5), 2)
eq("Round 1.25", vba.Round(1.25, 1), 1.2)
eq("Int", vba.Int(3.9), 3)
eq("Fix", vba.Fix(3.9), 3)
local r = vba.Rnd()
eq("Rnd range", r >= 0 and r < 1, true)

-- ===== Date/Time（序列号锚点：2024-01-01=45292, 1900-01-01=2, 2001-01-01=36892）=====
eq("DateSerial 2024-01-15", vba.DateSerial(2024, 1, 15), 45306)
eq("DateSerial 1900-01-01", vba.DateSerial(1900, 1, 1), 2)
eq("DateSerial clamp", vba.DateSerial(2024, 2, 31), 45351) -- 2024-02-29
eq("DateSerial m13", vba.DateSerial(2000, 13, 1), 36892) -- 2001-01-01
eq("DateValue", vba.DateValue("2024-01-15"), 45306)
eq("TimeSerial", vba.TimeSerial(0, 0, 0), 0)
eq("TimeSerial 12h", vba.TimeSerial(12, 0, 0), 0.5)
eq("Day", vba.Day(vba.DateSerial(2024, 5, 17)), 17)
eq("Month", vba.Month(vba.DateSerial(2024, 5, 17)), 5)
eq("Year", vba.Year(vba.DateSerial(2024, 5, 17)), 2024)
eq("Weekday mon", vba.Weekday(vba.DateSerial(2024, 1, 15)), 2) -- 周一
eq("Weekday sun", vba.Weekday(vba.DateSerial(2024, 1, 14)), 1) -- 周日
eq("MonthName", vba.MonthName(1), "January")
eq("MonthName abbr", vba.MonthName(1, true), "Jan")
eq("WeekdayName", vba.WeekdayName(1), "Sunday")
eq("DateAdd d", vba.DateAdd("d", 1, vba.DateSerial(2024, 1, 15)), 45307)
eq("DateAdd m clamp", vba.DateAdd("m", 1, vba.DateSerial(2024, 1, 31)), 45351) -- 2024-02-29
eq("DateAdd yyyy", vba.DateAdd("yyyy", 1, vba.DateSerial(2024, 1, 15)), vba.DateSerial(2025, 1, 15))
eq("DateDiff yyyy", vba.DateDiff("yyyy", vba.DateSerial(2000, 1, 1), vba.DateSerial(2024, 1, 1)), 24)
eq("DateDiff m", vba.DateDiff("m", vba.DateSerial(2024, 1, 1), vba.DateSerial(2024, 5, 1)), 4)
eq("DateDiff d", vba.DateDiff("d", vba.DateSerial(2024, 1, 1), vba.DateSerial(2024, 1, 15)), 14)
eq("DatePart q", vba.DatePart("q", vba.DateSerial(2024, 5, 1)), 2)
eq("DatePart yyyy", vba.DatePart("yyyy", vba.DateSerial(2024, 5, 1)), 2024)
eq("DatePart ww", vba.DatePart("ww", vba.DateSerial(2024, 1, 1)), 1)
eq("CDate", vba.CDate("2024-01-15"), 45306)
eq("Format 0.00", vba.Format(3.14159, "0.00"), "3.14")
eq("Format thous", vba.Format(1234567.891, "#,##0.00"), "1,234,567.89")
eq("Format pct", vba.Format(0.125, "0.00%"), "12.50%")
eq("Format date", vba.Format("2024-01-15", "yyyy-mm-dd"), "2024-01-15")

-- ===== Information / Array =====
local a = vba.Array("x", "y", "z")
eq("Array 0based", a[0], "x")
eq("Array len", vba.UBound(a), 2)
eq("LBound", vba.LBound(a), 0)
eq("IIf true", vba.IIf(1 < 2, "t", "f"), "t")
eq("IIf false", vba.IIf(1 > 2, "t", "f"), "f")
eq("IsNumeric str", tostring(vba.IsNumeric("123")), "true")
eq("IsNumeric sci", tostring(vba.IsNumeric("1.5e3")), "true")
eq("IsNumeric no", tostring(vba.IsNumeric("abc")), "false")
eq("IsDate str", tostring(vba.IsDate("2024-01-15")), "true")
eq("IsEmpty nil", tostring(vba.IsEmpty(nil)), "true")
eq("Choose", vba.Choose(2, "a", "b", "c"), "b")
eq("Switch", vba.Switch(false, "a", true, "b"), "b")
eq("RGB r", vba.RGB(255, 0, 0), 255)
eq("RGB g", vba.RGB(0, 255, 0), 65280)
eq("QBColor red", vba.QBColor(4), 128)
eq("Environ", type(vba.Environ("HOME")), "string")

print(string.format("vbamod test: ok=%d fail=%d", ok, fail))
if fail > 0 then os.exit(1) end
